# https://docs.microsoft.com/de-de/azure/devops/pipelines/agents/hosted?view=azure-devops#software
trigger:
- master

variables:
  python-version: "3.7"
  conan-pkg: "conan"
  cpt-pkg:  "conan_package_tools"
  bpt-pkg: "bincrafters_package_tools"

jobs:
  - job: Linux
    variables:
      CONAN_TOTAL_PAGES: 4
    strategy:
      matrix:
        Clang 7.0 x86_64:
          CONAN_CLANG_VERSIONS: 7.0
          CONAN_DOCKER_IMAGE: conanio/clang7
          CONAN_ARCHS: "x86_64"
          CONAN_CURRENT_PAGE: 4
    steps:
      - task: UsePythonVersion@0
        inputs:
         versionSpec: $(python-version)
      - script: |
          export PATH="$PATH:/home/vsts/.local/bin"
          sudo apt install -y python3-setuptools
          pip install --user --upgrade pip
          pip install --user $(conan-pkg)
          pip install --user $(cpt-pkg) $(bpt-pkg)
          conan user
          mkdir build
          cd build
          conan install ..
        displayName: conan create package
 